FROM node:16.14

WORKDIR /usr/src/app


COPY ./package.json ./

RUN npm install
# Build args
ARG REACT_APP_API_ROOT_URL

ENV REACT_APP_API_ROOT_URL = $REACT_APP_API_ROOT_URL

COPY . .


EXPOSE 3000

CMD ["npm","start"]
